// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/setup/backoffice/httpserver.go
//
// Generated by this command:
//
//	mockgen -source=cmd/setup/backoffice/httpserver.go -destination=./mocks/mockbackoffice/mock_httpserver.go -package=mockbackoffice
//

// Package mockbackoffice is a generated GoMock package.
package mockbackoffice

import (
	context "context"
	reflect "reflect"

	domain "github.com/IsaacDSC/gqueue/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockInsightsStore is a mock of InsightsStore interface.
type MockInsightsStore struct {
	ctrl     *gomock.Controller
	recorder *MockInsightsStoreMockRecorder
	isgomock struct{}
}

// MockInsightsStoreMockRecorder is the mock recorder for MockInsightsStore.
type MockInsightsStoreMockRecorder struct {
	mock *MockInsightsStore
}

// NewMockInsightsStore creates a new mock instance.
func NewMockInsightsStore(ctrl *gomock.Controller) *MockInsightsStore {
	mock := &MockInsightsStore{ctrl: ctrl}
	mock.recorder = &MockInsightsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInsightsStore) EXPECT() *MockInsightsStoreMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockInsightsStore) GetAll(ctx context.Context) (domain.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].(domain.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockInsightsStoreMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockInsightsStore)(nil).GetAll), ctx)
}
