### REGISTER A NEW CONSUMER
POST http://localhost:8080/event/consumer
Content-Type: application/json

{
  "name": "payment.processed",
  "service_name": "example-service",
  "repo_url": "github.com/example/repo",
  "team_owner": "example-team",
  "triggers": [
    {
      "service_name": "example-service-consumer",
      "type": "persistent",
      "host": "http://localhost:3333",
      "path": "/worker-queue/payment/processed",
      "headers": {
        "Content-Type": "application/json"
      },
      "option": {
        "queue_type": "external.medium",
        "max_retries": 3,
        "retention": "168h",
        "unique_ttl": "60s"
      }
    }
  ]
}

### Get events
GET http://localhost:8080/events/example-service?service-name=epayment.processed
Content-Type: application/json

### Publish External Event
POST http://localhost:8080/event/publisher
Content-Type: application/json

{
  "event_name": "user.created",
  "data": {
    "userId": "123e4567-e89b-12d3-a456-426614174000",
    "email": "user@example.com",
    "name": "John Doe"
  }
}


####
GET http://localhost:8080/tasks/archived/external.medium
Content-Type: application/json