// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interstore/mem_store.go
//
// Generated by this command:
//
//	mockgen -source=internal/interstore/mem_store.go -destination=./mocks/mockinterstore/mock_mem_store.go -package=mockinterstore
//

// Package mockinterstore is a generated GoMock package.
package mockinterstore

import (
	context "context"
	reflect "reflect"

	domain "github.com/IsaacDSC/gqueue/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPersistentStore is a mock of PersistentStore interface.
type MockPersistentStore struct {
	ctrl     *gomock.Controller
	recorder *MockPersistentStoreMockRecorder
	isgomock struct{}
}

// MockPersistentStoreMockRecorder is the mock recorder for MockPersistentStore.
type MockPersistentStoreMockRecorder struct {
	mock *MockPersistentStore
}

// NewMockPersistentStore creates a new mock instance.
func NewMockPersistentStore(ctrl *gomock.Controller) *MockPersistentStore {
	mock := &MockPersistentStore{ctrl: ctrl}
	mock.recorder = &MockPersistentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistentStore) EXPECT() *MockPersistentStoreMockRecorder {
	return m.recorder
}

// GetAllEvents mocks base method.
func (m *MockPersistentStore) GetAllEvents(ctx context.Context) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEvents", ctx)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEvents indicates an expected call of GetAllEvents.
func (mr *MockPersistentStoreMockRecorder) GetAllEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEvents", reflect.TypeOf((*MockPersistentStore)(nil).GetAllEvents), ctx)
}
