// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/taskapp/external_handle_http.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/taskapp/external_handle_http.go -destination=internal/app/taskapp/external_handle_http_mock.go -package=taskapp Store,PublisherInsights
//

// Package taskapp is a generated GoMock package.
package taskapp

import (
	context "context"
	reflect "reflect"

	domain "github.com/IsaacDSC/gqueue/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisherInsights is a mock of PublisherInsights interface.
type MockPublisherInsights struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherInsightsMockRecorder
	isgomock struct{}
}

// MockPublisherInsightsMockRecorder is the mock recorder for MockPublisherInsights.
type MockPublisherInsightsMockRecorder struct {
	mock *MockPublisherInsights
}

// NewMockPublisherInsights creates a new mock instance.
func NewMockPublisherInsights(ctrl *gomock.Controller) *MockPublisherInsights {
	mock := &MockPublisherInsights{ctrl: ctrl}
	mock.recorder = &MockPublisherInsightsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherInsights) EXPECT() *MockPublisherInsightsMockRecorder {
	return m.recorder
}

// Published mocks base method.
func (m *MockPublisherInsights) Published(ctx context.Context, input domain.PublisherMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Published", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Published indicates an expected call of Published.
func (mr *MockPublisherInsightsMockRecorder) Published(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Published", reflect.TypeOf((*MockPublisherInsights)(nil).Published), ctx, input)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetEvent mocks base method.
func (m *MockStore) GetEvent(ctx context.Context, eventName string) (domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, eventName)
	ret0, _ := ret[0].(domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockStoreMockRecorder) GetEvent(ctx, eventName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockStore)(nil).GetEvent), ctx, eventName)
}
