// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/pubadapter/adapter.go
//
// Generated by this command:
//
//	mockgen -source=pkg/pubadapter/adapter.go -destination=pkg/publisher/publisher_task_mock.go -package=publisher
//

// Package publisher is a generated GoMock package.
package publisher

import (
	context "context"
	reflect "reflect"

	pubadapter "github.com/IsaacDSC/gqueue/pkg/pubadapter"
	gomock "go.uber.org/mock/gomock"
)

// MockGenericPublisher is a mock of GenericPublisher interface.
type MockGenericPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockGenericPublisherMockRecorder
	isgomock struct{}
}

// MockGenericPublisherMockRecorder is the mock recorder for MockGenericPublisher.
type MockGenericPublisherMockRecorder struct {
	mock *MockGenericPublisher
}

// NewMockGenericPublisher creates a new mock instance.
func NewMockGenericPublisher(ctrl *gomock.Controller) *MockGenericPublisher {
	mock := &MockGenericPublisher{ctrl: ctrl}
	mock.recorder = &MockGenericPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenericPublisher) EXPECT() *MockGenericPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockGenericPublisher) Publish(ctx context.Context, topicName string, payload any, opts pubadapter.Opts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, topicName, payload, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockGenericPublisherMockRecorder) Publish(ctx, topicName, payload, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockGenericPublisher)(nil).Publish), ctx, topicName, payload, opts)
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisher) Publish(ctx context.Context, wqtype pubadapter.WQType, topicName string, payload any, opts pubadapter.Opts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, wqtype, topicName, payload, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(ctx, wqtype, topicName, payload, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), ctx, wqtype, topicName, payload, opts)
}
