// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/setup/pubsub/base.go
//
// Generated by this command:
//
//	mockgen -source=cmd/setup/pubsub/base.go -destination=./mocks/mockpubsub/mock_base.go -package=mockpubsub
//

// Package mockpubsub is a generated GoMock package.
package mockpubsub

import (
	context "context"
	reflect "reflect"

	domain "github.com/IsaacDSC/gqueue/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPersistentRepository is a mock of PersistentRepository interface.
type MockPersistentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPersistentRepositoryMockRecorder
	isgomock struct{}
}

// MockPersistentRepositoryMockRecorder is the mock recorder for MockPersistentRepository.
type MockPersistentRepositoryMockRecorder struct {
	mock *MockPersistentRepository
}

// NewMockPersistentRepository creates a new mock instance.
func NewMockPersistentRepository(ctrl *gomock.Controller) *MockPersistentRepository {
	mock := &MockPersistentRepository{ctrl: ctrl}
	mock.recorder = &MockPersistentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistentRepository) EXPECT() *MockPersistentRepositoryMockRecorder {
	return m.recorder
}

// GetAllEvents mocks base method.
func (m *MockPersistentRepository) GetAllEvents(ctx context.Context) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEvents", ctx)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEvents indicates an expected call of GetAllEvents.
func (mr *MockPersistentRepositoryMockRecorder) GetAllEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEvents", reflect.TypeOf((*MockPersistentRepository)(nil).GetAllEvents), ctx)
}

// GetAllSchedulers mocks base method.
func (m *MockPersistentRepository) GetAllSchedulers(ctx context.Context, state string) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSchedulers", ctx, state)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSchedulers indicates an expected call of GetAllSchedulers.
func (mr *MockPersistentRepositoryMockRecorder) GetAllSchedulers(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSchedulers", reflect.TypeOf((*MockPersistentRepository)(nil).GetAllSchedulers), ctx, state)
}
