// Code generated by mockgen. DO NOT EDIT.
// Source: internal/interstore/mem_store.go

package interstore

import (
	"context"
	"github.com/IsaacDSC/gqueue/internal/domain"
	"go.uber.org/mock/gomock"
	"reflect"
)

type MockPersistentStore struct {
	ctrl     *gomock.Controller
	recorder *MockPersistentStoreMockRecorder
}

type MockPersistentStoreMockRecorder struct {
	mock *MockPersistentStore
}

func NewMockPersistentStore(ctrl *gomock.Controller) *MockPersistentStore {
	mock := &MockPersistentStore{ctrl: ctrl}
	mock.recorder = &MockPersistentStoreMockRecorder{mock}
	return mock
}

func (m *MockPersistentStore) EXPECT() *MockPersistentStoreMockRecorder {
	return m.recorder
}

func (m *MockPersistentStore) GetAllEvents(ctx context.Context) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEvents", ctx)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPersistentStoreMockRecorder) GetAllEvents(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEvents", reflect.TypeOf((*MockPersistentStore)(nil).GetAllEvents), ctx)
}
