// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/taskapp/cache_store.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/taskapp/cache_store.go -destination=./mocks/mocktaskapp/mock_cache_store.go -package=mocktaskapp
//

// Package mocktaskapp is a generated GoMock package.
package mocktaskapp

import (
	context "context"
	reflect "reflect"

	taskapp "github.com/IsaacDSC/gqueue/internal/app/taskapp"
	domain "github.com/IsaacDSC/gqueue/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCacher is a mock of Cacher interface.
type MockCacher struct {
	ctrl     *gomock.Controller
	recorder *MockCacherMockRecorder
	isgomock struct{}
}

// MockCacherMockRecorder is the mock recorder for MockCacher.
type MockCacherMockRecorder struct {
	mock *MockCacher
}

// NewMockCacher creates a new mock instance.
func NewMockCacher(ctrl *gomock.Controller) *MockCacher {
	mock := &MockCacher{ctrl: ctrl}
	mock.recorder = &MockCacherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacher) EXPECT() *MockCacherMockRecorder {
	return m.recorder
}

// FindAllConsumers mocks base method.
func (m *MockCacher) FindAllConsumers(ctx context.Context) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllConsumers", ctx)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllConsumers indicates an expected call of FindAllConsumers.
func (mr *MockCacherMockRecorder) FindAllConsumers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllConsumers", reflect.TypeOf((*MockCacher)(nil).FindAllConsumers), ctx)
}

// FindAllQueues mocks base method.
func (m *MockCacher) FindAllQueues(ctx context.Context) ([]taskapp.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllQueues", ctx)
	ret0, _ := ret[0].([]taskapp.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllQueues indicates an expected call of FindAllQueues.
func (mr *MockCacherMockRecorder) FindAllQueues(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllQueues", reflect.TypeOf((*MockCacher)(nil).FindAllQueues), ctx)
}

// FindArchivedTasks mocks base method.
func (m *MockCacher) FindArchivedTasks(ctx context.Context, queue string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindArchivedTasks", ctx, queue)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindArchivedTasks indicates an expected call of FindArchivedTasks.
func (mr *MockCacherMockRecorder) FindArchivedTasks(ctx, queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindArchivedTasks", reflect.TypeOf((*MockCacher)(nil).FindArchivedTasks), ctx, queue)
}

// GetMsgArchivedTask mocks base method.
func (m *MockCacher) GetMsgArchivedTask(ctx context.Context, queue, task string) (taskapp.RawMsg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMsgArchivedTask", ctx, queue, task)
	ret0, _ := ret[0].(taskapp.RawMsg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMsgArchivedTask indicates an expected call of GetMsgArchivedTask.
func (mr *MockCacherMockRecorder) GetMsgArchivedTask(ctx, queue, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMsgArchivedTask", reflect.TypeOf((*MockCacher)(nil).GetMsgArchivedTask), ctx, queue, task)
}

// RemoveItemsArchivedTasks mocks base method.
func (m *MockCacher) RemoveItemsArchivedTasks(ctx context.Context, queue string, tasks ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, queue}
	for _, a := range tasks {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveItemsArchivedTasks", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItemsArchivedTasks indicates an expected call of RemoveItemsArchivedTasks.
func (mr *MockCacherMockRecorder) RemoveItemsArchivedTasks(ctx, queue any, tasks ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, queue}, tasks...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItemsArchivedTasks", reflect.TypeOf((*MockCacher)(nil).RemoveItemsArchivedTasks), varargs...)
}

// RemoveMsgArchivedTask mocks base method.
func (m *MockCacher) RemoveMsgArchivedTask(ctx context.Context, queue, task string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMsgArchivedTask", ctx, queue, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMsgArchivedTask indicates an expected call of RemoveMsgArchivedTask.
func (mr *MockCacherMockRecorder) RemoveMsgArchivedTask(ctx, queue, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMsgArchivedTask", reflect.TypeOf((*MockCacher)(nil).RemoveMsgArchivedTask), ctx, queue, task)
}

// SetArchivedTasks mocks base method.
func (m *MockCacher) SetArchivedTasks(ctx context.Context, events []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetArchivedTasks", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetArchivedTasks indicates an expected call of SetArchivedTasks.
func (mr *MockCacherMockRecorder) SetArchivedTasks(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetArchivedTasks", reflect.TypeOf((*MockCacher)(nil).SetArchivedTasks), ctx, events)
}
