// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/taskapp/archived_task.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/taskapp/archived_task.go -destination=./mocks/mocktaskapp/mock_archived_task.go -package=mocktaskapp
//

// Package mocktaskapp is a generated GoMock package.
package mocktaskapp

import (
	context "context"
	reflect "reflect"

	taskapp "github.com/IsaacDSC/gqueue/internal/app/taskapp"
	domain "github.com/IsaacDSC/gqueue/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheManager is a mock of CacheManager interface.
type MockCacheManager struct {
	ctrl     *gomock.Controller
	recorder *MockCacheManagerMockRecorder
	isgomock struct{}
}

// MockCacheManagerMockRecorder is the mock recorder for MockCacheManager.
type MockCacheManagerMockRecorder struct {
	mock *MockCacheManager
}

// NewMockCacheManager creates a new mock instance.
func NewMockCacheManager(ctrl *gomock.Controller) *MockCacheManager {
	mock := &MockCacheManager{ctrl: ctrl}
	mock.recorder = &MockCacheManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheManager) EXPECT() *MockCacheManagerMockRecorder {
	return m.recorder
}

// FindAllConsumers mocks base method.
func (m *MockCacheManager) FindAllConsumers(ctx context.Context) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllConsumers", ctx)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllConsumers indicates an expected call of FindAllConsumers.
func (mr *MockCacheManagerMockRecorder) FindAllConsumers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllConsumers", reflect.TypeOf((*MockCacheManager)(nil).FindAllConsumers), ctx)
}

// FindAllQueues mocks base method.
func (m *MockCacheManager) FindAllQueues(ctx context.Context) ([]taskapp.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllQueues", ctx)
	ret0, _ := ret[0].([]taskapp.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllQueues indicates an expected call of FindAllQueues.
func (mr *MockCacheManagerMockRecorder) FindAllQueues(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllQueues", reflect.TypeOf((*MockCacheManager)(nil).FindAllQueues), ctx)
}

// FindArchivedTasks mocks base method.
func (m *MockCacheManager) FindArchivedTasks(ctx context.Context, queue string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindArchivedTasks", ctx, queue)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindArchivedTasks indicates an expected call of FindArchivedTasks.
func (mr *MockCacheManagerMockRecorder) FindArchivedTasks(ctx, queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindArchivedTasks", reflect.TypeOf((*MockCacheManager)(nil).FindArchivedTasks), ctx, queue)
}

// GetMsgArchivedTask mocks base method.
func (m *MockCacheManager) GetMsgArchivedTask(ctx context.Context, queue, task string) (taskapp.RawMsg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMsgArchivedTask", ctx, queue, task)
	ret0, _ := ret[0].(taskapp.RawMsg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMsgArchivedTask indicates an expected call of GetMsgArchivedTask.
func (mr *MockCacheManagerMockRecorder) GetMsgArchivedTask(ctx, queue, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMsgArchivedTask", reflect.TypeOf((*MockCacheManager)(nil).GetMsgArchivedTask), ctx, queue, task)
}

// RemoveItemsArchivedTasks mocks base method.
func (m *MockCacheManager) RemoveItemsArchivedTasks(ctx context.Context, queue string, tasks ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, queue}
	for _, a := range tasks {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveItemsArchivedTasks", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItemsArchivedTasks indicates an expected call of RemoveItemsArchivedTasks.
func (mr *MockCacheManagerMockRecorder) RemoveItemsArchivedTasks(ctx, queue any, tasks ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, queue}, tasks...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItemsArchivedTasks", reflect.TypeOf((*MockCacheManager)(nil).RemoveItemsArchivedTasks), varargs...)
}

// RemoveMsgArchivedTask mocks base method.
func (m *MockCacheManager) RemoveMsgArchivedTask(ctx context.Context, queue, task string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMsgArchivedTask", ctx, queue, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMsgArchivedTask indicates an expected call of RemoveMsgArchivedTask.
func (mr *MockCacheManagerMockRecorder) RemoveMsgArchivedTask(ctx, queue, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMsgArchivedTask", reflect.TypeOf((*MockCacheManager)(nil).RemoveMsgArchivedTask), ctx, queue, task)
}

// SetArchivedTasks mocks base method.
func (m *MockCacheManager) SetArchivedTasks(ctx context.Context, events []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetArchivedTasks", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetArchivedTasks indicates an expected call of SetArchivedTasks.
func (mr *MockCacheManagerMockRecorder) SetArchivedTasks(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetArchivedTasks", reflect.TypeOf((*MockCacheManager)(nil).SetArchivedTasks), ctx, events)
}

// MockStorer is a mock of Storer interface.
type MockStorer struct {
	ctrl     *gomock.Controller
	recorder *MockStorerMockRecorder
	isgomock struct{}
}

// MockStorerMockRecorder is the mock recorder for MockStorer.
type MockStorerMockRecorder struct {
	mock *MockStorer
}

// NewMockStorer creates a new mock instance.
func NewMockStorer(ctrl *gomock.Controller) *MockStorer {
	mock := &MockStorer{ctrl: ctrl}
	mock.recorder = &MockStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorer) EXPECT() *MockStorerMockRecorder {
	return m.recorder
}

// GetAllSchedulers mocks base method.
func (m *MockStorer) GetAllSchedulers(ctx context.Context, state string) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSchedulers", ctx, state)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSchedulers indicates an expected call of GetAllSchedulers.
func (mr *MockStorerMockRecorder) GetAllSchedulers(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSchedulers", reflect.TypeOf((*MockStorer)(nil).GetAllSchedulers), ctx, state)
}
