// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/taskapp/consumer_handle.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/taskapp/consumer_handle.go -destination=./mocks/mocktaskapp/mock_consumer_handle.go -package=mocktaskapp
//

// Package mocktaskapp is a generated GoMock package.
package mocktaskapp

import (
	context "context"
	reflect "reflect"

	domain "github.com/IsaacDSC/gqueue/internal/domain"
	notifyopt "github.com/IsaacDSC/gqueue/internal/notifyopt"
	gomock "go.uber.org/mock/gomock"
)

// MockFetcher is a mock of Fetcher interface.
type MockFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockFetcherMockRecorder
	isgomock struct{}
}

// MockFetcherMockRecorder is the mock recorder for MockFetcher.
type MockFetcherMockRecorder struct {
	mock *MockFetcher
}

// NewMockFetcher creates a new mock instance.
func NewMockFetcher(ctrl *gomock.Controller) *MockFetcher {
	mock := &MockFetcher{ctrl: ctrl}
	mock.recorder = &MockFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetcher) EXPECT() *MockFetcherMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockFetcher) Notify(ctx context.Context, data map[string]any, headers map[string]string, consumer domain.Consumer, opt notifyopt.Kind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, data, headers, consumer, opt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockFetcherMockRecorder) Notify(ctx, data, headers, consumer, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockFetcher)(nil).Notify), ctx, data, headers, consumer, opt)
}

// MockConsumerInsights is a mock of ConsumerInsights interface.
type MockConsumerInsights struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerInsightsMockRecorder
	isgomock struct{}
}

// MockConsumerInsightsMockRecorder is the mock recorder for MockConsumerInsights.
type MockConsumerInsightsMockRecorder struct {
	mock *MockConsumerInsights
}

// NewMockConsumerInsights creates a new mock instance.
func NewMockConsumerInsights(ctrl *gomock.Controller) *MockConsumerInsights {
	mock := &MockConsumerInsights{ctrl: ctrl}
	mock.recorder = &MockConsumerInsightsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerInsights) EXPECT() *MockConsumerInsightsMockRecorder {
	return m.recorder
}

// Consumed mocks base method.
func (m *MockConsumerInsights) Consumed(ctx context.Context, input domain.ConsumerMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consumed", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consumed indicates an expected call of Consumed.
func (mr *MockConsumerInsightsMockRecorder) Consumed(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consumed", reflect.TypeOf((*MockConsumerInsights)(nil).Consumed), ctx, input)
}
