{
 "title": "Gqueue - Backoffice Service Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"postgres\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scope Backoffice ",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "# Backoffice message visualization\n\nData visualization, monitoring activity\n"
   }
  },
  {
   "title": "Backoffice Service CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "100 * sum(rate(process_cpu_seconds_total{job=\"gqueue-backoffice\"}[5m])) by (job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backoffice Service Mem (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"gqueue-backoffice\"}) by (job, instance) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backoffice Service Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"gqueue-backoffice\"}) by (job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backoffice Service Threads Go process",
   "type": "timeseries",
   "description": "O que a métrica representa na prática\nSe go_threads = 18, significa que o runtime Go está usando 18 threads do SO para executar:\n\ngoroutines da aplicação\ntrabalho de GC\noperações de rede / syscalls\nscheduler interno do runtime",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(go_threads{job=\"gqueue-backoffice\"}) by (job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backoffice service GC activity (min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "60 * rate(go_gc_duration_seconds_count{job=\"gqueue-backoffice\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scope Task ",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "# Database visualization\n\nData visualization, monitoring activity\n"
   }
  },
  {
   "title": "Total Conn ",
   "type": "stat",
   "description": "Total de conexões abertas Painel stat ou timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{job=\"postgres\", datname=\"gqueue\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GB disc",
   "type": "stat",
   "description": "Tamanho do banco em GB Painel stat",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"postgres\", datname=\"gqueue\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit ratio Painel",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(pg_stat_database_blks_hit{job=\"postgres\", datname=\"gqueue\"}[5m]))\n/\n(\n  sum(rate(pg_stat_database_blks_hit{job=\"postgres\", datname=\"gqueue\"}[5m]))\n  +\n  sum(rate(pg_stat_database_blks_read{job=\"postgres\", datname=\"gqueue\"}[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disc Reading",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{job=\"postgres\", datname=\"gqueue\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}