{
 "title": "Gqueue - Task Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scope Task ",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Tasks message visualization\n\nData visualization, monitoring activity\n"
   }
  },
  {
   "title": "Processing consumer task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (task_event_name) (task_consumer_total_processing)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success consumer task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum by (task_event_name) (task_consumer_success_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure consumer task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum by (task_event_name) (task_consumer_failure_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher Latency p95(s)",
   "type": "stat",
   "description": "P95 last 1m\n\nExemplo prático:\n- Se a query retornar `0.420` para `http_route=\"/api/v1/task\"`, significa que:\n  - nos últimos 1 minuto,\n  - 95% das requests dessa rota\n  - responderam em até `420 ms`.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(http_server_request_duration_seconds_bucket{job=\"gqueue-task\", http_route=\"/api/v1/task\"}[1m])) by (le, http_route, service_name)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Publisher RPM ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 * sum(rate(http_server_request_duration_seconds_count{job=\"gqueue-task\"}[1m])) by (http_route, service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Consumer RPM ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 * sum(rate(task_consumer_success_total{job=\"gqueue-task\"}[1m])) by (task_event_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM - Task Client HTTP Delivery ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "60 * sum(rate(http_client_request_duration_seconds_count{job=\"gqueue-task\"}[1m])) by (http_url, service_name, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scope Pubsub ",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "# MemStore task visualization\n\nData visualization, monitoring activity\n"
   }
  },
  {
   "title": "Task MemStrore Sync per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "60 * sum(rate(mem_store_activity_duration_count{job=\"gqueue-task\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync MemStore Time execution (Ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\n(\n  sum(rate(mem_store_activity_duration_sum{job=\"gqueue-task\"}[5m])) by (job)\n  /\n  sum(rate(mem_store_activity_duration_count{job=\"gqueue-task\"}[5m])) by (job)\n)\nand on(job)\nsum(rate(mem_store_activity_duration_count{job=\"gqueue-task\"}[5m])) by (job) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scope Pubsub ",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "# Task Service Metrics Visualization\n\nData visualization, monitoring activity\n"
   }
  },
  {
   "title": "Task Service CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "100 * sum(rate(process_cpu_seconds_total{job=\"gqueue-task\"}[5m])) by (job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Service Mem (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"gqueue-task\"}) by (job, instance) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Service Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"gqueue-task\"}) by (job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Service Threads Go process",
   "type": "timeseries",
   "description": "O que a métrica representa na prática\nSe go_threads = 18, significa que o runtime Go está usando 18 threads do SO para executar:\n\ngoroutines da aplicação\ntrabalho de GC\noperações de rede / syscalls\nscheduler interno do runtime",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(go_threads{job=\"gqueue-task\"}) by (job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task service GC activity (min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "60 * rate(go_gc_duration_seconds_count{job=\"gqueue-task\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}